[project]
name = "monopy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
    "projects/core/btb",
    "projects/tools/recording_parser",
]
